apiVersion: external-secrets.io/v1

kind: ExternalSecret

metadata:

  name: database-secret

  namespace: enterprise

spec:

  refreshInterval: 1h

  secretStoreRef:

    name: aws-secret-store

    kind: SecretStore

  target:

    name: app-secret

    creationPolicy: Owner

  data:

  - secretKey: username

    remoteRef:

      key: enterprise-devops-dev-db-secret

      property: username

  - secretKey: password

    remoteRef:

      key: enterprise-devops-dev-db-secret

      property: password