apiVersion: external-secrets.io/v1

kind: SecretStore

metadata:

  name: aws-secret-store

  namespace: enterprise

spec:

  provider:

    aws:

      service: SecretsManager

      region: ap-south-2

      auth:

        jwt:

          serviceAccountRef:

            name: external-secrets-sa