apiVersion: v1

kind: ServiceAccount

metadata:

  name: external-secrets-sa

  namespace: enterprise

  annotations:

    eks.amazonaws.com/role-arn: arn:aws:iam::705557196379:role/ExternalSecretsRole