apiVersion: v1
kind: Service

metadata:

  name: {{ include "enterprise-app.fullname" . }}

spec:

  type: {{ .Values.service.type }}

  selector:

    app: {{ include "enterprise-app.name" . }}

  ports:

  - port: {{ .Values.service.port }}

    targetPort: {{ .Values.containerPort }}

    protocol: TCP