name: Continuous Delivery

on:
  workflow_run:
    workflows:
      - Continuous Integration
    types:
      - completed

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Print workflow_run details
        run: |
          echo "Workflow Name: ${{ github.event.workflow_run.name }}"
          echo "Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Head Branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Head SHA: ${{ github.event.workflow_run.head_sha }}"
          echo "Repository: ${{ github.repository }}"