name: Enterprise Deployment Pipeline

on:

  push:

    branches:

      - feature/secrets

      - main

jobs:

  deploy:

    runs-on: ubuntu-latest


    defaults:
      run:
       working-directory: app

    steps:

      ##########################################################
      # Checkout
      ##########################################################

      - name: Checkout Repository

        uses: actions/checkout@v4

      ##########################################################
      # Configure AWS
      ##########################################################

      - name: Configure AWS Credentials

        uses: aws-actions/configure-aws-credentials@v4

        with:

          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          aws-region: ${{ secrets.AWS_REGION }}

      ##########################################################
      # Read Secret
      ##########################################################

      - name: Retrieve Database Secret

      #  id: secret

        run: |

          SECRET=$(aws secretsmanager get-secret-value \
            --secret-id ${{ secrets.SECRET_NAME }} \
            --query SecretString \
            --output text)

          DB_USERNAME=$(echo $SECRET | jq -r '.username')

          DB_PASSWORD=$(echo $SECRET | jq -r '.password')

          echo "DB_USERNAME=$DB_USERNAME" >> $GITHUB_ENV

          echo "DB_PASSWORD=$DB_PASSWORD" >> $GITHUB_ENV

      ##########################################################
      # Display Secret Length
      ##########################################################

      - name: Verify Secret

        run: |

          echo "Secret retrieved successfully."

          echo $DB_SECRET | jq .

      ##########################################################
      # Docker Build
      ##########################################################

      - name: Build Docker Image

        run: |

          docker build \
          --build-arg DB_USERNAME=$DB_USERNAME \
          --build-arg DB_PASSWORD=$DB_PASSWORD \
          -t enterprise-app .

      ##########################################################
      # Deployment
      ##########################################################

      - name: Deploy

        run: |

          echo "Deploying Application..."